version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_DB: car_adverts
      POSTGRES_USER: avrdoljak
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: